<p>Your <a href="https://dtf.digital"><strong>DTF Digital</strong></a> extension's are licensed for use on the website: <strong><?php echo $this->getBaseUrl(); ?></strong><br /><br /></p>

<h2>If you need support with any of your extensions, please email:</h2>
<p><a href="mailto:support@dtf.digital?subject=I need support with a DTF Digital M2 Extension">support@dtf.digital</a><br /><br /></p>
<p>Please include as much detail as possible, including your order number, Magento 2 version, and steps to replicate your problem.</p>